IOC_TOP = /home/laci/Repos/ads-ioc
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = TwinCAT Project1
PROJECT_PATH := ../../TC_project/TwinCAT Project1/TwinCAT Project1/TwinCAT Project1.tsproj
PLC = Untitled1

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
